global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'service-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'local'

  - job_name: 'service-monitor'
    scrape_interval: 5s
    static_configs:
      - targets: ['url-shortener-service:8080']
        labels:
          group: 'url-shortener'