version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
      - image: mongo:3.6.8

    working_directory: /go/src/github.com/woraphol-j/url-shortener

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      # Install dependencies
      - run: dep ensure

      - run:
          name: Waiting for Mongo to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 27017 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Mongo && exit 1
      - run:
          name: Run unit and integration tests
          command: |
            TEST_RESULTS=/tmp/test-results/ginkgo MONGO_URL=mongodb://localhost:27017 MONGO_DATABASE=url-shortener MONGO_COLLECTION=urls go test ./...

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
