apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 0
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        # image: ${DOCKER_PREFIX}/${SERVICE}:${VERSION}
        image: gcr.io/pilot-154919/url-shortener:1.7
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            # port: 80
        envFrom:
        - configMapRef:
            name: url-shortener
        env:
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: url-shortener
  name: url-shortener
spec:
  selector:
    app: url-shortener
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener
data:
  APP_PORT: "8080"
  BASE_URL: http://localhost:8080
  MYSQL_HOST: 10.93.192.3
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: url_shortener
